import type { DetailGroup } from "./types";

// Verbatim capability catalogs from the updated content deliverable (reference/1.docx).
// Shared between the Industries pages ("Detailed [X] Solutions") and the Expertise >
// Domain/Functions pages ("Detailed Domain Solutions") — the two placements list identical
// items in the source document.
export const verticalCapabilityLayers: Record<string, DetailGroup[]> = {
  manufacturing: [
    {
      title: "Machine Learning & Predictive Intelligence",
      items: [
        "AI Demand Forecasting",
        "Real-Time Demand Sensing",
        "Sales & Operations Planning (S&OP)",
        "Integrated Business Planning (IBP)",
        "Forecast Accuracy Intelligence",
        "Customer Demand Analytics",
        "Promotion Planning",
        "Price Optimization",
        "Procurement Intelligence",
        "Spend Analytics",
        "Supplier Risk Management",
        "Supplier Performance Analytics",
        "Price Benchmarking",
        "Production Planning & Capacity Planning",
        "Production Scheduling",
        "OEE Intelligence",
        "Manufacturing Analytics",
        "Process Optimization",
        "Asset Health Intelligence",
        "Machine Health Monitoring",
        "Remaining Useful Life Prediction",
        "Inventory Optimization",
        "Warehouse Intelligence",
        "Route Optimization",
        "Fleet Intelligence",
        "Executive KPI Intelligence",
        "Root Cause Analytics",
      ],
    },
    {
      title: "Generative AI Solutions",
      items: [
        "Manufacturing Copilot",
        "Procurement Copilot",
        "Supply Chain Copilot",
        "Executive Copilot",
        "Contract Intelligence",
        "RFQ/RFP Automation",
        "Document Intelligence",
        "Enterprise Knowledge Assistant",
        "Intelligent Reporting",
        "Enterprise Search",
      ],
    },
    {
      title: "Agentic AI & Autonomous Operations",
      items: [
        "Autonomous Planning Agents",
        "Autonomous Procurement Agents",
        "Autonomous Manufacturing Agents",
        "Autonomous Maintenance Agents",
        "Demand Intelligence Agents",
        "Procurement Intelligence Agents",
        "Production Intelligence Agents",
        "Warehouse Intelligence Agents",
        "Logistics Intelligence Agents",
        "Multi-Agent Manufacturing Orchestrators",
      ],
    },
  ],
  "oil-gas": [
    {
      title: "Machine Learning & Predictive Intelligence",
      items: [
        "Refinery Process Optimization",
        "Yield Optimization",
        "Crude Blend Optimization",
        "Production Planning",
        "Capacity Planning",
        "Production Forecasting",
        "Feedstock Optimization",
        "Product Allocation Intelligence",
        "Throughput Optimization",
        "Predictive Maintenance",
        "Asset Performance Management",
        "Equipment Health Monitoring",
        "Reliability Analytics",
        "Corrosion Monitoring",
        "Remaining Useful Life Prediction",
        "Process Safety Analytics",
        "Incident Prediction",
        "Risk Intelligence",
        "Emissions Monitoring",
        "Supply Chain Visibility",
        "Pipeline Monitoring",
        "Fleet Intelligence",
        "Distribution Planning",
        "Market Intelligence",
        "Pricing Analytics",
        "Trading Risk Analytics",
        "Margin Optimization",
        "Energy Consumption Analytics",
        "Carbon Emissions Intelligence",
        "Executive KPI Intelligence",
      ],
    },
    {
      title: "Generative AI Solutions",
      items: [
        "Operations Copilot",
        "Maintenance Copilot",
        "HSE Copilot",
        "Executive Copilot",
        "Engineering Knowledge Assistant",
        "Document Intelligence",
        "Enterprise Search",
        "Intelligent Reporting",
        "Regulatory Knowledge Assistant",
      ],
    },
    {
      title: "Agentic AI & Autonomous Operations",
      items: [
        "Autonomous Production Planning Agents",
        "Maintenance Intelligence Agents",
        "Safety Compliance Agents",
        "Logistics Intelligence Agents",
        "Trading Intelligence Agents",
        "Executive Intelligence Agents",
        "Multi-Agent Operations Orchestrators",
      ],
    },
  ],
  insurance: [
    {
      title: "Machine Learning & Predictive Intelligence",
      items: [
        "Intelligent Risk Assessment",
        "AI-Powered Underwriting",
        "Automated Risk Scoring",
        "Premium Pricing Optimization",
        "Customer Risk Profiling",
        "Portfolio Risk Analytics",
        "Claims Severity Prediction",
        "Claims Settlement Optimization",
        "Fraud Risk Scoring",
        "Behavioral Fraud Analytics",
        "Network Fraud Analytics",
        "Enterprise Risk Analytics",
        "Predictive Risk Intelligence",
        "Catastrophe Risk Modeling",
        "Customer Segmentation",
        "Customer Lifetime Value Analytics",
        "Customer Churn Prediction",
        "Next Best Action Intelligence",
      ],
    },
    {
      title: "Generative AI Solutions",
      items: [
        "Underwriting Copilot",
        "Claims Copilot",
        "Customer Service Copilot",
        "Executive Copilot",
        "Policy Document Intelligence",
        "Claims Document Intelligence",
        "Conversational AI",
      ],
    },
    {
      title: "Agentic AI & Autonomous Operations",
      items: [
        "Autonomous Underwriting Agents",
        "Claims Processing Agents",
        "Fraud Intelligence Agents",
        "Customer Engagement Agents",
        "Policy Administration Agents",
        "Risk Intelligence Agents",
        "Multi-Agent Insurance Operations Orchestrators",
      ],
    },
  ],
  healthcare: [
    {
      title: "Machine Learning & Predictive Intelligence",
      items: [
        "Patient Journey Intelligence",
        "Clinical Decision Intelligence",
        "Medical Imaging Analytics",
        "Hospital Operations Intelligence",
        "Bed Utilization Analytics",
        "Workforce Planning",
        "Revenue Cycle Intelligence",
        "Predictive Readmissions",
        "Population Health Intelligence",
        "Claims Intelligence",
        "Payment Integrity Intelligence",
        "Care Management Intelligence",
        "Provider Network Intelligence",
        "Regulatory Risk Intelligence",
        "Member Experience Intelligence",
        "Utilization Management",
        "Fraud, Waste & Abuse Detection",
      ],
    },
    {
      title: "Generative AI Solutions",
      items: [
        "Clinical Copilot",
        "Care Management Copilot",
        "Claims Copilot",
        "Member Service Copilot",
        "Healthcare Knowledge Assistant",
        "Medical Document Intelligence",
        "Conversational AI",
        "Executive Healthcare Copilot",
      ],
    },
    {
      title: "Agentic AI & Autonomous Operations",
      items: [
        "Patient Engagement Agents",
        "Clinical Workflow Agents",
        "Claims Processing Agents",
        "Care Management Agents",
        "Utilization Management Agents",
        "Executive Healthcare Agents",
        "Multi-Agent Healthcare Orchestrators",
      ],
    },
  ],
  pharmaceuticals: [
    {
      title: "Machine Learning & Predictive Intelligence",
      items: [
        "Smart Pharma Manufacturing",
        "Batch Production Intelligence",
        "Equipment Monitoring",
        "CAPA Intelligence",
        "GMP Compliance",
        "Commercial Analytics",
        "Sales Force Effectiveness",
        "Market Access Intelligence",
        "Product Risk Mitigation Analysis",
      ],
    },
    {
      title: "Generative AI Solutions",
      items: [
        "Research Intelligence Analyst",
        "Regulatory Copilot",
        "Quality Copilot",
        "Pharmacovigilance Copilot",
        "Medical Affairs Copilot",
        "Scientific Knowledge Assistant",
        "Regulatory Document Intelligence",
      ],
    },
    {
      title: "Agentic AI & Autonomous Operations",
      items: [
        "Manufacturing & Quality Agents",
        "Regulatory Affairs Agents",
        "Pharmacovigilance Agents",
        "Supply Chain & Cold Chain Logistics Agents",
        "Product Risk Mitigation Agents",
        "Multi-Agent Pharmaceutical Operations Orchestrators",
      ],
    },
  ],
};
